# Generated by Django 5.2.9 on 2025-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description/notes'),
        ),
        migrations.AddField(
            model_name='availability',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title/note for this availability', max_length=200),
        ),
    ]
