# Generated by Django 5.2.9 on 2025-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availability_description_availability_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(help_text="ISO country code (e.g., 'US', 'GB', 'CA')", max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_national', models.BooleanField(default=True, help_text='Whether this is a national holiday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'country'], name='core_holida_date_009dd1_idx')],
                'unique_together': {('date', 'name', 'country')},
            },
        ),
    ]
